### ISSUE TITLE
Effect API

### ISSUE THREAD

**Issue by Zilacon** [Zilacon/APOC-RPG#2]
Replace potion effects with a effect API that adds the following "enhancements" to gear that can be upgraded using another socket with the same effect.

Sockets should now be based off of the effect they give, removing the entire need of rolling for a enhancement. Now a socket drops with its own effect with its own gear priorities.

Gems are the replacement of sockets with potion effects. Instead of having a huge bonus that is simply over powering. We now have gems that give small bonuses and can be upgraded when merging gems of the same type into a item. So if you socket a sword with a Gem of Ravaging it now has increased damage. And the damage will be increased when you socket the sword again with another Gem of ravaging.

The percent values increase the total amount of stats that the item already holds. For example if a sword has 10 damage and it is increased by 10% it now has 11 damage.

ALL GEMS HAVE UP TO 10 UPGRADES. Gems can be upgraded by right clicking a gem then right clicking a item with a (Socket) in it. And the gem in the socketed item can be upgraded by repeating the process with another gem of the same type.

## Armor Gems: Helmets, Chestplates, Leggings, Boots
Gem of Impact: All damage dealt to the wearer when receiving fall damage will be dealt to all enemies within a 3 block (+1 block per upgrade) radius. (This is nullified if the wearer has fall protection, as the damage from falling is reduced the damage to the enemies around them is reduced.)
Gem of Nullify: Reduced the duration of impaired effects by 5% (+5% per upgrade). So if an enemy poisons you for 10 seconds and you have 50% nullify the duration will be 5 seconds.
-DONE-Gem of Warding: Adds 10% armor / +2.5% per upgrade / Max of 25%
-DONE-Gem of Velocity:  Adds 10% movement speed / +2.5% per upgrade / Max of 25%
-DONE-Gem of Vaulting: Increases jump height by 0.5 blocks / +0.25 blocks per upgrade / Max of 3 blocks.
-DONE-Gem of Staggering: Adds nausea for 1s when hit / +0.25s per upgrade / Max of 2.5s | Does not stack.
-DONE-Gem of Demons: Adds 10% chance to resist fire attacks when hit. / +2.5% per upgrade / Max of 25%
-DONE-Gem of Healing (AURA): Adds a ❤ regeneration aura for a 1 block radius. / +1 block per upgrade / Max of 7 blocks.
-DONE-Gem of Damage (AURA): Adds a +15% Damage aura for a 1 block radius. / +1 block per upgrade / Max of 7 blocks.
-DONE-Gem of Resistance (AURA): Adds a +15% damage resistance aura for a 1 block radius / +1 block per upgrade / Max of 7 blocks.
-DONE-Gem of Speed (AURA): Adds a +15% movement speed aura for a 1 block radius / +1 block per upgrade / Max of 7 blocks.
-DONE-Gem of Taunting (AURA): Adds a 5 block mob attraction aura. / +5 blocks per upgrade.
Gem of Courage (AURA): Adds +2.5% Resistance for every enemy within a 5 block radius. / +2.5% & 1 block radius per upgrade.
Gem of Synchro (AURA): Copies the effect of an aura near you (5 blocks / +1 block per upgrade) from other players and doubles the effects. The copied/doubled aura will stack on top of the copied aura and will be shared with all players within the radius.

## Passive Weapon Gems: Axes, Bows, Swords
-DONE-Gem of Ravaging: Adds 10% damage / +2.5% per upgrade / Max of 25%
-DONE-Gem of Decapitation: Adds 10% chance to drop a head on kill / +2.5% per upgrade / Max of 25%

## On Hit Weapon Gems: Axes, Bows, Swords
-DONE-Gem of Debilitation: Decreases movement speed by 2.5% / +2.5% per upgrade / Max of 17.5%
-DONE-Gem of Crippling: Reduces enemies damage by 10% / +5% per upgrade / Max of 40% (0.4/1.0 Hearts)
-DONE-Gem of Bloodthirst: Adds 0.25 ❤ per Hit / +0.15 ❤PH Per Upgrade / Max of 1.15 ❤PH
-DONE-Gem of Blinding: Adds 5% chance to blind for 1s on hit / +0.25s per upgrade / Max of 2.5s
-DONE-Gem of Sacrifice: Adds 2.5% chance to deal 200% damage at the cost of 2.5 ❤ / +1.5% per upgrade / Max of 11.5%
Gem of Force: 2.5% (+0.75 per upgrade) chance to deal 50% additional damage to the enemy.
Gem of Venom: Poisons the enemy for 1 second (+1.5 seconds per upgrade). (This can use the poison potion/food poisoning effect with a reduced duration)

## On Hit Weapon Gems: Swords & Axes
-DONE-Gem of Slashing: Adds 5% chance to Bleed / +1.5% per upgrade / Max of 14% | 0.25 ❤ DOT per SEC for 3 Seconds.
-DONE-Gem of Cleaving: Adds 5% chance to Cleave / +1.5% per upgrade / Max of 14% | Damages enemies within a 1.5 block radius.

## On Hit Weapon Gems: Bows
-DONE-Gem of Hell: Adds a 2.5% chance to fire a fireball / +1.5% per upgrade / Max of 11.5%
-DONE-Gem of Multishot: Adds a 2.5% chance to fire 2 arrows / +1.5% per upgrade / Max of 11.5%
-DONE-Gem of Blast: Adds 2.5% chance to knockback enemies within a 1.5 block radius of the arrow / +1.5% per upgrade / Max of 11.5%

## Tool Gems: Shovel, Pickaxe, Hoe, Shears, Fishing Rod
-DONE-Gem of Breaking: Blocks break 10% faster / +2.5% per upgrade / Max of 25%
Gem of Demolition: 2.5% chance (+1.5% chance per upgrade) to explode the blocks around the block broken (acts like vanilla TNT).
Gem of Smelting: 10% chance (+10% per upgrade) to automatically smelt ores when broken. (Smelts all ores including forge modded ores)

Still working on this...

**Comment by unarmed1618** [comment]
Effects are being done one by one.

**Comment by unarmed1618** [comment]
Testing is now the primary concern. Please test each gem and report on effectiveness

**Comment by Zilacon** [comment]
Need a compiled version/release to test.

**Comment by beardedknight** [comment]
Compiling the latest commit, [6117feccd59b022382b847cdd65c2c869c283503](https://github.com/Zilacon/APOC-RPG/commit/6117feccd59b022382b847cdd65c2c869c283503), created this [APOC-RPG.jar] (https://www.dropbox.com/s/j182rg6mgmhqudv/APOC-RPG.jar?dl=0).  Running the plugin generates the following error when engaging in combat of any type:
````
2015-02-15 18:21:17 [SEVERE] Could not pass event EntityDamageByEntityEvent to APOCRPG v0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
	at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
	at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:423)
	at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:967)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(EntityAnimal.java:206)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1544)
	at net.minecraft.network.NetServerHandler.func_72507_a(NetServerHandler.java:1644)
	at net.minecraft.network.packet.Packet7UseEntity.func_73279_a(Packet7UseEntity.java:57)
	at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:463)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
	at com.APOCRPG.Events.CombatEvents.onHit(CombatEvents.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
	... 21 more
````

**Comment by beardedknight** [comment]
Alright after looking at the code, figured out the problem.  The getEffectsFromItem() function in EffectsApi.java returns a null string if nothing is generated (as expected).  But the events that are calling them, i.e. CombatEvents.java, EntityEvents.java are not checking for a null value'd return.  They are operating on the assumption something's being returned back that isn't null.

**Comment by beardedknight** [comment]
Fixed the issue by making the EffectAPI.getEffectsFromItem() function return a Hashmap regardless - no null values returned.  The Hashmap is uninitialized, but it is still a Hashmap that is returned.  [https://github.com/beardedknight/APOC-RPG/commit/edaaf20e7a448c2eebfb389230285be39ba7a199] (https://github.com/beardedknight/APOC-RPG/commit/edaaf20e7a448c2eebfb389230285be39ba7a199)

**Comment by Zilacon** [comment]
@beardedknight I added you as a collaborator. Download the github program and download the repo then update it with your changes and sync it, then sync any changes from here on out so its easier for wixoa to keep track of your progress.

Thanks!

**Comment by beardedknight** [comment]
Found another error, do I keep posting in this issue or create a new one?

**Comment by unarmed1618** [comment]
Also, @BeardedKnight, an uninitialized Hashmap is still a null value. It's a pointer that claims its a Hashmap which points to a null. 
As opposed to an empty Hashmap which is initialized and has nothing in it. 
>_<

**Comment by Zilacon** [comment]
@beardedknight Please make a new issue for each one.

**Comment by magicslayer** [comment]
In this open issue, it seems to say that gems are working but when I compile the jar and test it, the gems don't seem to do anything and I'm having a hard time finding the code that assigns each gem with an effect while it's equipped on an item.

**Comment by whiteknave** [comment]
I'm not at home, so I can't look at the code, but there should be an EffectsAPI.java class that handles some it. There should  also be an event listener class that is registered at startup that should apply the effects.

**Comment by whiteknave** [comment]
For arrows, its effects are handled in the ProjectileEvents.onShoot() class method. Armor events are handled in the PollingEventListener.poll() class method.  Weapon events are handled in the CombatEvents.onHit() class method.

**Comment by magicslayer** [comment]
lol, I didn't realize you emailed me. ^_^

**Comment by magicslayer** [comment]
Thanks, I think we've jumped the wall ^_^

**Comment by whiteknave** [comment]
I couldn't sleep so I went ahead and updated ApocRPGCommand.java so that ops can create specific gems.  The command is case sensitive.  Be sure to pull the latest code and export the jar.

1) Start your minetickmod server in a java console window (i use the non-gui command)
2) at the command line, op yourself:
    ">op <playername>"
3) startup minecraft and join your local server
4) enter the following command in minecraft
    "/apocrpg buy gem <effect name> <level>"
    for examples:
    "/apocrpg buy gem Warding 1"
    "/apocrpg buy gem Multishot 2"
    "/apocrpg buy gem Fortune 3"

the effect name is case sensitive and must match exactly the effect names in the EffectAPI.  The following command will result in an error:
    "/apocrpg buy gem warding 1"

**Comment by whiteknave** [comment]
I've also fixed being able to merge gems.
